// language: C++17, file: vanta_dll.cpp, target: Windows 11, MSVC
// VANTA Internal DLL — injected into Roblox, reads memory directly
// Uses offsets.h generated by offset_dumper.exe

#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#include <cstdint>
#include <cstdio>
#include <cmath>
#include <string>
#include <vector>
#include <thread>
#include <atomic>
#include <mutex>
#include <algorithm>

// ================================================================
// OFFSETS — generated by offset_dumper or hardcoded defaults
// ================================================================
namespace off {
    // Instance
    int Name = 0x70;
    int Children = 0x78;
    int Parent = 0x68;
    int ClassDescriptor = 0x18;
    int ClassName = 0x8;

    // DataModel
    int FDM_DataModel = 0x1F8;

    // Players
    int LocalPlayer = 0x130;

    // Camera
    int Camera_ViewMatrix = 0x150;

    // BasePart
    int CFrame = 0x110;

    // Humanoid
    int Health = 0x228;

    // Character ref on Player instance
    int Player_Character = 0x100;
}

// Try to load offsets.h values at runtime from a config file
static void load_offsets_config() {
    char path[MAX_PATH];
    GetModuleFileNameA(nullptr, path, MAX_PATH);
    std::string dir(path);
    size_t sl = dir.find_last_of("\\/");
    if (sl != std::string::npos) dir = dir.substr(0, sl + 1);
    std::string cfg = dir + "vanta_offsets.ini";

    FILE* f = fopen(cfg.c_str(), "r");
    if (!f) return;
    char line[256];
    while (fgets(line, sizeof(line), f)) {
        char key[64]; int val;
        if (sscanf(line, "%63[^=]=%i", key, &val) == 2) {
            std::string k(key);
            if (k == "Name") off::Name = val;
            else if (k == "Children") off::Children = val;
            else if (k == "Parent") off::Parent = val;
            else if (k == "FDM_DataModel") off::FDM_DataModel = val;
            else if (k == "LocalPlayer") off::LocalPlayer = val;
            else if (k == "Camera_ViewMatrix") off::Camera_ViewMatrix = val;
            else if (k == "CFrame") off::CFrame = val;
            else if (k == "Health") off::Health = val;
            else if (k == "Player_Character") off::Player_Character = val;
        }
    }
    fclose(f);
}

// ================================================================
// MEMORY — internal, direct pointer dereference
// ================================================================
template<typename T>
static T mem(uintptr_t addr) {
    __try { return *(T*)addr; }
    __except (EXCEPTION_EXECUTE_HANDLER) { return T{}; }
}

static std::string read_rstr(uintptr_t addr) {
    if (addr < 0x10000) return "";
    __try {
        uint64_t len = *(uint64_t*)(addr + 0x10);
        if (len == 0 || len > 200) return "";
        const char* buf = (len > 15) ? (const char*)*(uintptr_t*)addr : (const char*)addr;
        if ((uintptr_t)buf < 0x10000) return "";
        return std::string(buf, (size_t)len);
    } __except (EXCEPTION_EXECUTE_HANDLER) { return ""; }
}

static std::string inst_name(uintptr_t inst) {
    return read_rstr(mem<uintptr_t>(inst + off::Name));
}

static std::string inst_classname(uintptr_t inst) {
    uintptr_t cd = mem<uintptr_t>(inst + off::ClassDescriptor);
    if (cd < 0x10000) return "";
    return read_rstr(mem<uintptr_t>(cd + off::ClassName));
}

static std::vector<uintptr_t> get_children(uintptr_t inst) {
    std::vector<uintptr_t> out;
    uintptr_t cp = mem<uintptr_t>(inst + off::Children);
    if (cp < 0x10000) return out;
    uintptr_t start = mem<uintptr_t>(cp);
    uintptr_t end = mem<uintptr_t>(cp + 8);
    if (start < 0x10000 || end <= start || end - start > 0x50000) return out;
    for (uintptr_t p = start; p < end; p += 0x10) {
        uintptr_t c = mem<uintptr_t>(p);
        if (c > 0x10000) out.push_back(c);
    }
    return out;
}

static uintptr_t find_child(uintptr_t inst, const std::string& name) {
    for (uintptr_t c : get_children(inst))
        if (inst_name(c) == name) return c;
    return 0;
}

static uintptr_t find_child_class(uintptr_t inst, const std::string& cls) {
    for (uintptr_t c : get_children(inst))
        if (inst_classname(c) == cls) return c;
    return 0;
}

// ================================================================
// MATH
// ================================================================
struct Vec3 { float x, y, z; };
struct Vec2 { float x, y; };
struct Matrix4 { float m[4][4]; };

static Vec2 world_to_screen(const Vec3& pos, const Matrix4& vm, int w, int h) {
    float cx = vm.m[0][0]*pos.x + vm.m[1][0]*pos.y + vm.m[2][0]*pos.z + vm.m[3][0];
    float cy = vm.m[0][1]*pos.x + vm.m[1][1]*pos.y + vm.m[2][1]*pos.z + vm.m[3][1];
    float cw = vm.m[0][3]*pos.x + vm.m[1][3]*pos.y + vm.m[2][3]*pos.z + vm.m[3][3];
    if (cw < 0.001f) return {-1, -1};
    float nx = cx / cw;
    float ny = cy / cw;
    return { (1.0f + nx) * 0.5f * w, (1.0f - ny) * 0.5f * h };
}

static float dist3d(Vec3 a, Vec3 b) {
    float dx = a.x-b.x, dy = a.y-b.y, dz = a.z-b.z;
    return sqrtf(dx*dx + dy*dy + dz*dz);
}

// ================================================================
// PLAYER DATA
// ================================================================
struct PlayerInfo {
    std::string name;
    Vec3 position;
    float health;
    float max_health;
    Vec2 screen;
    bool on_screen;
    float distance;
};

// ================================================================
// GLOBALS
// ================================================================
static std::atomic<bool> g_running{true};
static std::mutex g_mtx;
static std::vector<PlayerInfo> g_players;

// Features
static std::atomic<bool> g_esp{true};
static std::atomic<bool> g_aimbot{false};
static std::atomic<bool> g_names{true};
static std::atomic<bool> g_health_bar{true};
static std::atomic<bool> g_boxes{true};
static std::atomic<bool> g_snaplines{false};
static std::atomic<bool> g_distance{true};
static std::atomic<float> g_aim_fov{200.0f};
static std::atomic<bool> g_menu_open{false};

static HWND g_hwnd = nullptr;
static int g_screen_w = 0, g_screen_h = 0;

// ================================================================
// DATAMODEL FINDER — scans from inside the process
// ================================================================
static uintptr_t find_datamodel() {
    // Scan .data section for FakeDataModel pointer
    HMODULE hmod = GetModuleHandleA(nullptr);
    if (!hmod) return 0;
    uintptr_t base = (uintptr_t)hmod;

    PIMAGE_DOS_HEADER dos = (PIMAGE_DOS_HEADER)base;
    PIMAGE_NT_HEADERS nt = (PIMAGE_NT_HEADERS)(base + dos->e_lfanew);
    PIMAGE_SECTION_HEADER sec = IMAGE_FIRST_SECTION(nt);

    for (int i = 0; i < nt->FileHeader.NumberOfSections; i++) {
        if (memcmp(sec[i].Name, ".data", 5) == 0 || memcmp(sec[i].Name, ".rdata", 6) == 0) {
            uintptr_t start = base + sec[i].VirtualAddress;
            uintptr_t size = sec[i].Misc.VirtualSize;
            for (uintptr_t a = start; a + 8 < start + size; a += 8) {
                __try {
                    uintptr_t fdm = *(uintptr_t*)a;
                    if (fdm < 0x10000 || fdm > 0x7FFFFFFFFFFF) continue;
                    uintptr_t dm = *(uintptr_t*)(fdm + off::FDM_DataModel);
                    if (dm < 0x10000) continue;
                    // Check children for known services
                    auto ch = get_children(dm);
                    int known = 0;
                    for (auto c : ch) {
                        std::string n = inst_name(c);
                        if (n == "Workspace" || n == "Players" || n == "Lighting" ||
                            n == "ReplicatedStorage" || n == "StarterGui")
                            known++;
                    }
                    if (known >= 3) return dm;
                } __except (EXCEPTION_EXECUTE_HANDLER) { continue; }
            }
        }
    }
    return 0;
}

// ================================================================
// PLAYER SCANNER THREAD
// ================================================================
static void scanner_thread() {
    uintptr_t dm = 0;
    while (g_running) {
        if (!dm) {
            dm = find_datamodel();
            if (!dm) { Sleep(1000); continue; }
        }

        // Verify DataModel still valid
        __try {
            auto ch = get_children(dm);
            bool has_players = false;
            for (auto c : ch) if (inst_name(c) == "Players") { has_players = true; break; }
            if (!has_players) { dm = 0; continue; }
        } __except (EXCEPTION_EXECUTE_HANDLER) { dm = 0; continue; }

        uintptr_t players = find_child(dm, "Players");
        uintptr_t workspace = find_child(dm, "Workspace");
        if (!players || !workspace) { Sleep(500); continue; }

        uintptr_t local_player = mem<uintptr_t>(players + off::LocalPlayer);
        if (local_player < 0x10000) { Sleep(200); continue; }

        std::string local_name = inst_name(local_player);

        // Get camera
        uintptr_t camera = find_child_class(workspace, "Camera");
        Matrix4 vm{};
        Vec3 cam_pos{};
        if (camera) {
            __try {
                memcpy(&vm, (void*)(camera + off::Camera_ViewMatrix), sizeof(Matrix4));
                // Camera CFrame position is usually at ViewMatrix offset - 0x30 or nearby
                cam_pos = mem<Vec3>(camera + off::CFrame);
            } __except (EXCEPTION_EXECUTE_HANDLER) {}
        }

        // Enumerate players
        std::vector<PlayerInfo> new_players;
        auto player_list = get_children(players);
        for (uintptr_t p : player_list) {
            std::string pname = inst_name(p);
            if (pname.empty() || pname == local_name) continue;

            // Find character — try known offsets
            uintptr_t character = 0;
            for (int co = off::Player_Character; co <= off::Player_Character + 0x40; co += 8) {
                uintptr_t ch = mem<uintptr_t>(p + co);
                if (ch < 0x10000) continue;
                if (find_child(ch, "HumanoidRootPart")) { character = ch; break; }
            }
            if (!character) continue;

            uintptr_t hrp = find_child(character, "HumanoidRootPart");
            uintptr_t humanoid = find_child(character, "Humanoid");
            if (!hrp) continue;

            Vec3 pos = mem<Vec3>(hrp + off::CFrame);
            if (pos.x == 0.0f && pos.y == 0.0f && pos.z == 0.0f) continue;

            float hp = 100.0f, max_hp = 100.0f;
            if (humanoid) {
                hp = mem<float>(humanoid + off::Health);
                max_hp = mem<float>(humanoid + off::Health + 4);
                if (max_hp <= 0.0f) max_hp = 100.0f;
                if (hp < 0.0f) hp = 0.0f;
            }

            Vec2 scr = world_to_screen(pos, vm, g_screen_w, g_screen_h);
            bool on = (scr.x >= 0 && scr.x < g_screen_w && scr.y >= 0 && scr.y < g_screen_h);

            // Get local player pos for distance
            Vec3 local_pos{};
            uintptr_t lchar = 0;
            for (int co = off::Player_Character; co <= off::Player_Character + 0x40; co += 8) {
                uintptr_t ch = mem<uintptr_t>(local_player + co);
                if (ch < 0x10000) continue;
                if (find_child(ch, "HumanoidRootPart")) { lchar = ch; break; }
            }
            if (lchar) {
                uintptr_t lhrp = find_child(lchar, "HumanoidRootPart");
                if (lhrp) local_pos = mem<Vec3>(lhrp + off::CFrame);
            }

            PlayerInfo pi;
            pi.name = pname;
            pi.position = pos;
            pi.health = hp;
            pi.max_health = max_hp;
            pi.screen = scr;
            pi.on_screen = on;
            pi.distance = dist3d(pos, local_pos);
            new_players.push_back(pi);
        }

        {
            std::lock_guard<std::mutex> lk(g_mtx);
            g_players = std::move(new_players);
        }
        Sleep(16); // ~60fps scan rate
    }
}

// ================================================================
// OVERLAY WINDOW
// ================================================================
static LRESULT CALLBACK overlay_wndproc(HWND hwnd, UINT msg, WPARAM wp, LPARAM lp) {
    if (msg == WM_DESTROY) { g_running = false; PostQuitMessage(0); return 0; }
    return DefWindowProcA(hwnd, msg, wp, lp);
}

static HWND create_overlay() {
    g_screen_w = GetSystemMetrics(SM_CXSCREEN);
    g_screen_h = GetSystemMetrics(SM_CYSCREEN);

    WNDCLASSEXA wc{};
    wc.cbSize = sizeof(wc);
    wc.lpfnWndProc = overlay_wndproc;
    wc.hInstance = GetModuleHandleA(nullptr);
    wc.lpszClassName = "VantaOverlay";
    wc.hbrBackground = (HBRUSH)GetStockObject(BLACK_BRUSH);
    RegisterClassExA(&wc);

    HWND hwnd = CreateWindowExA(
        WS_EX_TOPMOST | WS_EX_TRANSPARENT | WS_EX_LAYERED | WS_EX_TOOLWINDOW,
        "VantaOverlay", "",
        WS_POPUP,
        0, 0, g_screen_w, g_screen_h,
        nullptr, nullptr, wc.hInstance, nullptr
    );

    SetLayeredWindowAttributes(hwnd, RGB(0, 0, 0), 0, LWA_COLORKEY);
    ShowWindow(hwnd, SW_SHOW);
    UpdateWindow(hwnd);
    return hwnd;
}

// ================================================================
// RENDER
// ================================================================
static void draw_text(HDC hdc, int x, int y, const char* text, COLORREF color) {
    SetTextColor(hdc, color);
    SetBkMode(hdc, TRANSPARENT);
    TextOutA(hdc, x, y, text, (int)strlen(text));
}

static void draw_box(HDC hdc, int x, int y, int w, int h, COLORREF color) {
    HPEN pen = CreatePen(PS_SOLID, 2, color);
    HPEN old = (HPEN)SelectObject(hdc, pen);
    SelectObject(hdc, GetStockObject(NULL_BRUSH));
    Rectangle(hdc, x, y, x + w, y + h);
    SelectObject(hdc, old);
    DeleteObject(pen);
}

static void draw_line(HDC hdc, int x1, int y1, int x2, int y2, COLORREF color) {
    HPEN pen = CreatePen(PS_SOLID, 1, color);
    HPEN old = (HPEN)SelectObject(hdc, pen);
    MoveToEx(hdc, x1, y1, nullptr);
    LineTo(hdc, x2, y2);
    SelectObject(hdc, old);
    DeleteObject(pen);
}

static void draw_health_bar(HDC hdc, int x, int y, int h, float hp, float max_hp) {
    float ratio = (max_hp > 0) ? hp / max_hp : 1.0f;
    if (ratio > 1.0f) ratio = 1.0f;
    int bar_h = (int)(h * ratio);

    HBRUSH bg = CreateSolidBrush(RGB(40, 40, 40));
    RECT rbg = { x - 6, y, x - 2, y + h };
    FillRect(hdc, &rbg, bg);
    DeleteObject(bg);

    COLORREF hpcolor = RGB((int)(255 * (1 - ratio)), (int)(255 * ratio), 0);
    HBRUSH hp_br = CreateSolidBrush(hpcolor);
    RECT rhp = { x - 6, y + h - bar_h, x - 2, y + h };
    FillRect(hdc, &rhp, hp_br);
    DeleteObject(hp_br);
}

static void render_frame() {
    HDC hdc = GetDC(g_hwnd);
    HDC mem_dc = CreateCompatibleDC(hdc);
    HBITMAP bmp = CreateCompatibleBitmap(hdc, g_screen_w, g_screen_h);
    SelectObject(mem_dc, bmp);

    // Clear to black (transparent via colorkey)
    RECT rc = { 0, 0, g_screen_w, g_screen_h };
    HBRUSH black = CreateSolidBrush(RGB(0, 0, 0));
    FillRect(mem_dc, &rc, black);
    DeleteObject(black);

    HFONT font = CreateFontA(14, 0, 0, 0, FW_BOLD, 0, 0, 0,
        DEFAULT_CHARSET, 0, 0, ANTIALIASED_QUALITY, 0, "Consolas");
    SelectObject(mem_dc, font);

    if (g_esp) {
        std::lock_guard<std::mutex> lk(g_mtx);
        for (const auto& p : g_players) {
            if (!p.on_screen) continue;

            int sx = (int)p.screen.x;
            int sy = (int)p.screen.y;

            // Approximate box size based on distance
            float scale = 1000.0f / (p.distance + 100.0f);
            int bw = (int)(40.0f * scale);
            int bh = (int)(90.0f * scale);
            if (bw < 10) bw = 10;
            if (bh < 20) bh = 20;
            if (bw > 200) bw = 200;
            if (bh > 400) bh = 400;

            int bx = sx - bw / 2;
            int by = sy - bh;

            COLORREF color = (p.health > 50) ? RGB(0, 255, 0) : (p.health > 25) ? RGB(255, 255, 0) : RGB(255, 0, 0);

            if (g_boxes)
                draw_box(mem_dc, bx, by, bw, bh, color);

            if (g_names) {
                char buf[128];
                if (g_distance)
                    snprintf(buf, sizeof(buf), "%s [%.0fm]", p.name.c_str(), p.distance);
                else
                    snprintf(buf, sizeof(buf), "%s", p.name.c_str());
                draw_text(mem_dc, sx - (int)strlen(buf) * 3, by - 16, buf, RGB(255, 255, 255));
            }

            if (g_health_bar)
                draw_health_bar(mem_dc, bx, by, bh, p.health, p.max_health);

            if (g_snaplines)
                draw_line(mem_dc, g_screen_w / 2, g_screen_h, sx, sy, color);
        }
    }

    // Menu
    if (g_menu_open) {
        HBRUSH menu_bg = CreateSolidBrush(RGB(20, 20, 30));
        RECT menu_rc = { 50, 50, 350, 380 };
        FillRect(mem_dc, &menu_rc, menu_bg);
        DeleteObject(menu_bg);

        draw_box(mem_dc, 50, 50, 300, 330, RGB(100, 0, 200));

        int y = 60;
        draw_text(mem_dc, 70, y, "=== VANTA DLL ===", RGB(200, 100, 255)); y += 22;
        draw_text(mem_dc, 70, y, "[F1] ESP", g_esp ? RGB(0,255,0) : RGB(255,0,0)); y += 18;
        draw_text(mem_dc, 70, y, "[F2] Aimbot", g_aimbot ? RGB(0,255,0) : RGB(255,0,0)); y += 18;
        draw_text(mem_dc, 70, y, "[F3] Names", g_names ? RGB(0,255,0) : RGB(255,0,0)); y += 18;
        draw_text(mem_dc, 70, y, "[F4] Health Bars", g_health_bar ? RGB(0,255,0) : RGB(255,0,0)); y += 18;
        draw_text(mem_dc, 70, y, "[F5] Boxes", g_boxes ? RGB(0,255,0) : RGB(255,0,0)); y += 18;
        draw_text(mem_dc, 70, y, "[F6] Snaplines", g_snaplines ? RGB(0,255,0) : RGB(255,0,0)); y += 18;
        draw_text(mem_dc, 70, y, "[F7] Distance", g_distance ? RGB(0,255,0) : RGB(255,0,0)); y += 18;

        char fov_str[64]; snprintf(fov_str, sizeof(fov_str), "[F8/F9] Aim FOV: %.0f", g_aim_fov.load());
        draw_text(mem_dc, 70, y, fov_str, RGB(200, 200, 200)); y += 22;

        {
            std::lock_guard<std::mutex> lk(g_mtx);
            char pcount[64]; snprintf(pcount, sizeof(pcount), "Players: %d", (int)g_players.size());
            draw_text(mem_dc, 70, y, pcount, RGB(150, 150, 255)); y += 18;
        }

        draw_text(mem_dc, 70, y, "[INSERT] Toggle Menu", RGB(150, 150, 150)); y += 18;
        draw_text(mem_dc, 70, y, "[END] Eject DLL", RGB(255, 100, 100));
    }

    DeleteObject(font);

    BitBlt(hdc, 0, 0, g_screen_w, g_screen_h, mem_dc, 0, 0, SRCCOPY);
    DeleteObject(bmp);
    DeleteDC(mem_dc);
    ReleaseDC(g_hwnd, hdc);
}

// ================================================================
// AIMBOT
// ================================================================
static void aimbot_tick() {
    if (!g_aimbot || !(GetAsyncKeyState(VK_RBUTTON) & 0x8000)) return;

    float best_dist = g_aim_fov.load();
    Vec2 best_pos = {-1, -1};

    {
        std::lock_guard<std::mutex> lk(g_mtx);
        for (const auto& p : g_players) {
            if (!p.on_screen || p.health <= 0) continue;
            float dx = p.screen.x - g_screen_w / 2.0f;
            float dy = p.screen.y - g_screen_h / 2.0f;
            float d = sqrtf(dx * dx + dy * dy);
            if (d < best_dist) {
                best_dist = d;
                best_pos = p.screen;
            }
        }
    }

    if (best_pos.x >= 0) {
        float dx = best_pos.x - g_screen_w / 2.0f;
        float dy = best_pos.y - g_screen_h / 2.0f;
        // Smooth aim
        float smooth = 5.0f;
        int mx = (int)(dx / smooth);
        int my = (int)(dy / smooth);
        if (mx != 0 || my != 0)
            mouse_event(MOUSEEVENTF_MOVE, mx, my, 0, 0);
    }
}

// ================================================================
// INPUT
// ================================================================
static void input_thread() {
    while (g_running) {
        if (GetAsyncKeyState(VK_INSERT) & 1) g_menu_open = !g_menu_open;
        if (GetAsyncKeyState(VK_F1) & 1) g_esp = !g_esp;
        if (GetAsyncKeyState(VK_F2) & 1) g_aimbot = !g_aimbot;
        if (GetAsyncKeyState(VK_F3) & 1) g_names = !g_names;
        if (GetAsyncKeyState(VK_F4) & 1) g_health_bar = !g_health_bar;
        if (GetAsyncKeyState(VK_F5) & 1) g_boxes = !g_boxes;
        if (GetAsyncKeyState(VK_F6) & 1) g_snaplines = !g_snaplines;
        if (GetAsyncKeyState(VK_F7) & 1) g_distance = !g_distance;
        if (GetAsyncKeyState(VK_F8) & 1) { float f = g_aim_fov.load(); if (f > 50) g_aim_fov = f - 25.0f; }
        if (GetAsyncKeyState(VK_F9) & 1) { float f = g_aim_fov.load(); if (f < 500) g_aim_fov = f + 25.0f; }
        if (GetAsyncKeyState(VK_END) & 1) { g_running = false; break; }
        Sleep(30);
    }
}

// ================================================================
// MAIN THREAD
// ================================================================
static DWORD WINAPI main_thread(LPVOID) {
    AllocConsole();
    FILE* f;
    freopen_s(&f, "CONOUT$", "w", stdout);

    printf("\n  VANTA DLL — Internal Roblox Hack\n");
    printf("  [INSERT] Menu  |  [END] Eject\n\n");

    load_offsets_config();

    g_hwnd = create_overlay();
    if (!g_hwnd) {
        printf("[!] Failed to create overlay\n");
        return 1;
    }

    std::thread scanner(scanner_thread);
    std::thread input(input_thread);

    printf("[+] Scanner started\n");
    printf("[+] Overlay active — press INSERT for menu\n");

    MSG msg;
    while (g_running) {
        while (PeekMessageA(&msg, nullptr, 0, 0, PM_REMOVE)) {
            if (msg.message == WM_QUIT) { g_running = false; break; }
            TranslateMessage(&msg);
            DispatchMessageA(&msg);
        }
        render_frame();
        aimbot_tick();
        Sleep(8); // ~120fps render
    }

    printf("[*] Ejecting...\n");

    if (scanner.joinable()) scanner.join();
    if (input.joinable()) input.join();

    if (g_hwnd) DestroyWindow(g_hwnd);
    UnregisterClassA("VantaOverlay", GetModuleHandleA(nullptr));

    if (f) fclose(f);
    FreeConsole();
    FreeLibraryAndExitThread(GetModuleHandleA("vanta_dll.dll"), 0);
    return 0;
}

// ================================================================
// DLL ENTRY
// ================================================================
BOOL APIENTRY DllMain(HMODULE hModule, DWORD reason, LPVOID) {
    if (reason == DLL_PROCESS_ATTACH) {
        DisableThreadLibraryCalls(hModule);
        CreateThread(nullptr, 0, main_thread, hModule, 0, nullptr);
    }
    return TRUE;
}
